project_id = "nlytekhjmumtuabzhsur"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.translate]
verify_jwt = false

[functions.trial-reminder]
verify_jwt = false

[functions.analyze-pronunciation]
verify_jwt = false

[functions.roleplay-chat]
verify_jwt = false